### ISSUE TITLE
Cloud | Purchase and configure domain

### ISSUE THREAD

**Issue by Zenidd** [jahcuida/critical-mass#11]
Hey @jahcuida, after the poll to choose the domain name finishes we will need to buy and configure the domain.

I suggest purchasing the domain at AWS Route53 service (remember the issues we had with Google domains when configuring the root domain).

I think this ticket will require an effort of 2h

**Comment by jahcuida** [comment]
The domain has been purchased and configured correctly


![Image](https://github.com/jahcuida/critical-mass/assets/105076467/30aaad09-8b7d-45b3-93e8-3fe54ead7478)


![Image](https://github.com/jahcuida/critical-mass/assets/105076467/c86a45fa-54c6-43dc-835f-0a8a6a442c38)

**Comment by Zenidd** [comment]
The release was a success, congrats @jahcuida!!!

![DeoBmec](https://github.com/jahcuida/critical-mass/assets/14923294/d0fc8d33-3235-40b3-92c5-054839e238c5)
