### ISSUE TITLE
UI | Slider images distortion

### ISSUE THREAD

**Issue by Zenidd** [jahcuida/critical-mass#30]
Hey @jahcuida, hope you are doing well mate.

Yesterday I realised that the slider component is changing its width proportionally to the viewport size.

When that viewport is wide, the image is too wide

![image](https://github.com/jahcuida/critical-mass/assets/14923294/8947adf3-1d08-405b-ad7a-d62909d5633f)

The opposite happens with narrower viewport size
![image](https://github.com/jahcuida/critical-mass/assets/14923294/9bd447cf-4a86-4f49-8383-3613a4345a87)

I would like to work on this issue, what do you think?

**Comment by jahcuida** [comment]
I think  this issue should be fixed ASAP, so I will work on it this afternoon.

Thanks for the error notification 

Have a good day! :)
