### ISSUE TITLE
UI | Update image's date 

### ISSUE THREAD

**Issue by jahcuida** [jahcuida/critical-mass#32]
The date that appears on the main image should be updated. 

A generic date could be great since the celebration of the event is always the first friday of each month.

**Comment by Zenidd** [comment]
Hey @jahcuida,

Just updated the landing page banner with a new one.

I commited to the main branch directly, sorry cause I was not on my main pc and didn't have any terminal or code editor.

Seems like the AWS automation is still working properly as I can see the change on the site already

![image](https://github.com/jahcuida/critical-mass/assets/14923294/8f4e8eb1-2d53-4972-9e14-5c63c8bab047)

I'm closing the issue. Take care my boy

![8b63c2d89efacf6e35498ae2c8efdcbf](https://github.com/jahcuida/critical-mass/assets/14923294/cc866120-4ca7-4b24-b3d1-52f85493e8c5)

**Comment by Zenidd** [comment]
By the way, here is the commit with the change https://github.com/jahcuida/critical-mass/commit/15a519e7219c3a465db5da7f07ce5526069d2985
